version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
      - "5174:5174"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/contestsystem
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret
      - PORT=5000
      - FRONTEND_URL=http://localhost:5174
      - VITE_API_BASE_URL=http://localhost:5000/api
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
